version: '3.8'

services:
  # Future Orchestrator
  evtechallenge-orch:
    build: .
    container_name: evtechallenge-orch
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - prometheus
    networks:
      - evtechallenge_network

  # Elasticsearch for logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - evtechallenge_network

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - evtechallenge_network
  
  # Grafana for visualization
  grafana:
    image: grafana/grafana:12.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - elasticsearch
      - prometheus
    networks:
      - evtechallenge_network

volumes:
  elasticsearch_data:
  prometheus_data:
  grafana_data:

networks:
  evtechallenge_network:
    driver: bridge