{
 "title": "API REST - System Metrics",
 "tags": [
  "api-rest",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API REST - OS Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "api_go_threads{service=\"api-rest\"}"
    }
   ]
  },
  {
   "title": "API REST - Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "api_go_memstats_alloc_bytes{service=\"api-rest\"}"
    }
   ]
  },
  {
   "title": "API REST - System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "api_go_memstats_sys_bytes{service=\"api-rest\"}"
    }
   ]
  },
  {
   "title": "API REST - Active HTTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_active_connections" }
   ]
  }
 ]
}