apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
  
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: logs*
    uid: elasticsearch
    jsonData:
      timeField: "@timestamp"
      esVersion: 9.1.2
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
